# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOFKcCrTGljGtVm1js1zKiko5Jj2y9dl
"""

!pip install opencv-python
!pip install face_recognition
!pip install scikit-learn

from google.colab import drive
drive.mount('/content/drive')

# Define the source folder in Google Drive
source_folder = '/content/drive/MyDrive/Images'
target_folder = '/content/drive/MyDrive/sorted_images'

import face_recognition
import os
import shutil
from sklearn.cluster import DBSCAN
import numpy as np

def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img_path = os.path.join(folder, filename)
        img = face_recognition.load_image_file(img_path)
        if img is not None:
            images.append((filename, img))
    return images

def encode_faces(images):
    encodings = []
    for filename, img in images:
        face_encodings = face_recognition.face_encodings(img)
        for face_encoding in face_encodings:
            encodings.append((filename, face_encoding))
    return encodings

def cluster_faces(encodings, eps=0.5, min_samples=5):
    face_encodings = [encoding[1] for encoding in encodings]
    if len(face_encodings) == 0:
        return np.array([])  # Handle case with no encodings
    labels = DBSCAN(metric='euclidean', eps=eps, min_samples=min_samples, n_jobs=-1).fit_predict(face_encodings)
    return labels

def sort_images_by_person(encodings, labels):
    persons = {}
    for idx, label in enumerate(labels):
        filename, encoding = encodings[idx]
        if label not in persons:
            persons[label] = []
        persons[label].append(filename)

    # Remove duplicates and preserve the order of first occurrences
    for label, files in persons.items():
        persons[label] = list(dict.fromkeys(files))

    return persons

def create_folders_and_move_images(persons, source_folder, target_folder):
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)

    for person_id, files in persons.items():
        person_folder = os.path.join(target_folder, f'person_{person_id}')
        if not os.path.exists(person_folder):
            os.makedirs(person_folder)

        for file in files:
            src_file_path = os.path.join(source_folder, file)
            dest_file_path = os.path.join(person_folder, file)
            if not os.path.exists(dest_file_path):
                shutil.copy(src_file_path, dest_file_path)

# Use this if you mounted Google Drive
source_folder = '/content/drive/MyDrive/Images'
target_folder = '/content/sorted_images'

# Step-by-step process
images = load_images_from_folder(source_folder)
encodings = encode_faces(images)

# Tune the eps and min_samples parameters if needed
eps = 0.6
min_samples = 3
labels = cluster_faces(encodings, eps=eps, min_samples=min_samples)

persons = sort_images_by_person(encodings, labels)
create_folders_and_move_images(persons, source_folder, target_folder)

from google.colab import drive
drive.mount('/content/drive')

# Download the sorted images folder as a zip file
from google.colab import files
!zip -r sorted_images.zip /content/sorted_images
files.download('sorted_images.zip')

